### ISSUE TITLE
Only include Active agreements when calculating median, average and total for AvtaleGiro and Vipps at home page

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#158]
"Median agreement sum" for Vipps is obviously including more than only active agreements. Not confirmed that the other statistics are including more than "Active".

**Comment by mortenkjelling** [comment]
This is backend-work, and should probably be moved to that repo (https://github.com/stiftelsen-effekt/effekt-backend)
Not too fond of writing sql these days, so someone else should take a look.
Can be found in the `getAgreementReport` in `DAO_modules/avtalegiroagreements.js` and `DAO_modules/vipps.js` 
Just make sure to keep the same format as before since this is used in effekt-admin.

**Comment by JorgenLjones** [comment]
Why is this issue closed @fellmirr?
The median is stille not calculated correctly for both Vipps and AvtaleGiro, but Average seems correct.

**Comment by fellmirr** [comment]
@JorgenLjones Ops, it must have been closed by mistake. Or possibly I changed it so that the total was only active or something, and forgot about the median. I'll reopen and fix.
